[2025-08-14T06:27:58.343+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_main_script_runner.run_main_py scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T06:27:58.363+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_main_script_runner.run_main_py scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T06:27:58.363+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-08-14T06:27:58.394+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): run_main_py> on 2025-08-13 00:00:00+00:00
[2025-08-14T06:27:58.400+0000] {standard_task_runner.py:60} INFO - Started process 821 to run task
[2025-08-14T06:27:58.411+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'weather_main_script_runner', 'run_main_py', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/weather_batch_dag.py', '--cfg-path', '/tmp/tmpv5cylri4']
[2025-08-14T06:27:58.414+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask run_main_py
[2025-08-14T06:27:58.526+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_main_script_runner.run_main_py scheduled__2025-08-13T00:00:00+00:00 [running]> on host 3e49ce6b9cd3
[2025-08-14T06:27:58.703+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_main_script_runner' AIRFLOW_CTX_TASK_ID='run_main_py' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T06:27:58.704+0000] {logging_mixin.py:188} INFO - Running Python script: /opt/infra/pyspark_jobs
[2025-08-14T06:27:58.784+0000] {logging_mixin.py:188} INFO - STDOUT:
[2025-08-14T06:27:58.785+0000] {logging_mixin.py:188} INFO -  
[2025-08-14T06:27:58.785+0000] {logging_mixin.py:188} INFO - STDERR:
[2025-08-14T06:27:58.785+0000] {logging_mixin.py:188} INFO -  /usr/local/bin/python3: can't find '__main__' module in '/opt/infra/pyspark_jobs'
[2025-08-14T06:27:58.786+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/weather_batch_dag.py", line 22, in run_weather_main
    raise RuntimeError(f"Script failed with exit code {result.returncode}")
RuntimeError: Script failed with exit code 1
[2025-08-14T06:27:58.804+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_main_script_runner, task_id=run_main_py, execution_date=20250813T000000, start_date=20250814T062758, end_date=20250814T062758
[2025-08-14T06:27:58.820+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 33 for task run_main_py (Script failed with exit code 1; 821)
[2025-08-14T06:27:58.859+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T06:27:58.903+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
