[2025-08-13T08:04:12.875+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_batch_processing.run_weather_batch_script manual__2025-08-13T08:04:11.291294+00:00 [queued]>
[2025-08-13T08:04:12.892+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_batch_processing.run_weather_batch_script manual__2025-08-13T08:04:11.291294+00:00 [queued]>
[2025-08-13T08:04:12.893+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-08-13T08:04:12.922+0000] {taskinstance.py:2192} INFO - Executing <Task(SparkSubmitOperator): run_weather_batch_script> on 2025-08-13 08:04:11.291294+00:00
[2025-08-13T08:04:12.931+0000] {standard_task_runner.py:60} INFO - Started process 231 to run task
[2025-08-13T08:04:12.935+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'weather_batch_processing', 'run_weather_batch_script', 'manual__2025-08-13T08:04:11.291294+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/weather_batch_dag.py', '--cfg-path', '/tmp/tmpievfeprw']
[2025-08-13T08:04:12.939+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask run_weather_batch_script
[2025-08-13T08:04:13.110+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_batch_processing.run_weather_batch_script manual__2025-08-13T08:04:11.291294+00:00 [running]> on host b8abf4c23708
[2025-08-13T08:04:13.416+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_batch_processing' AIRFLOW_CTX_TASK_ID='run_weather_batch_script' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T08:04:11.291294+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-13T08:04:11.291294+00:00'
[2025-08-13T08:04:13.450+0000] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2025-08-13T08:04:13.453+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master yarn --name weather_batch_job --verbose --queue root.default /home/neosoft/Desktop/wheather_analytics_trends/pyspark_jobs/process_weather_data.py
[2025-08-13T08:04:17.570+0000] {spark_submit.py:649} INFO - Using properties file: null
[2025-08-13T08:04:17.828+0000] {spark_submit.py:649} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2025-08-13T08:04:17.829+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2025-08-13T08:04:17.830+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2025-08-13T08:04:17.831+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2025-08-13T08:04:17.831+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2025-08-13T08:04:17.832+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1108)
[2025-08-13T08:04:17.832+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1108)
[2025-08-13T08:04:17.833+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2025-08-13T08:04:17.833+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1125)
[2025-08-13T08:04:17.834+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1134)
[2025-08-13T08:04:17.834+0000] {spark_submit.py:649} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-08-13T08:04:17.906+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 575, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name weather_batch_job --verbose --queue root.default /home/neosoft/Desktop/wheather_analytics_trends/pyspark_jobs/process_weather_data.py. Error code is: 1.
[2025-08-13T08:04:17.915+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_batch_processing, task_id=run_weather_batch_script, execution_date=20250813T080411, start_date=20250813T080412, end_date=20250813T080417
[2025-08-13T08:04:17.943+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2 for task run_weather_batch_script (Cannot execute: spark-submit --master yarn --name weather_batch_job --verbose --queue root.default /home/neosoft/Desktop/wheather_analytics_trends/pyspark_jobs/process_weather_data.py. Error code is: 1.; 231)
[2025-08-13T08:04:18.003+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-13T08:04:18.034+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
